spring.application.name=personal-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/personal_trainer
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true